name: Deploy to Hugging Face
on:
  push:
    branches: [main] # Il deploy parte quando fai un push su main
  workflow_dispatch: # Ti permette di farlo partire anche a mano

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Forza il push del codice verso lo Space di Hugging Face
          git push --force https://xmignax:$HF_TOKEN@huggingface.co/spaces/xmignax/JackProxy main
